network:
  version: 2
  # Note that even though this should be listed as `wifis` with a mode of `ap`,
  # netplan won't allow it, because ubuntu server uses networkd, which doesn't
  # support access points...
  ethernets:
    # You can customize other things in this file if you wish.  I had to add my wifi interface manually
    wlp3s0:
      addresses: []
      dhcp4: true
      optional: true
  bridges:
    br0:
      # Change these interface names to match your needs
      interfaces: [enp6s0, wlp3s0]
      dhcp4: true
      # optional: true
      # `address` and `netmask` from ifupdown - @see https://askubuntu.com/questions/972955/ubuntu-17-10-server-static-ip-netplan-how-to-set-netmask
      # `broadcast` from ifupdown is no longer needed - @see https://unix.stackexchange.com/questions/446217/broadcast-and-network-in-netplan
      addresses: [192.168.1.1/24]
      # `network` from ifupdown
      gateway4: 192.168.1.0
