network:
  version: 2
  ethernets:
    # You can customize other things in this file if you wish.  I had to add my wifi interface manually
    wlp5s0:
      addresses: []
      dhcp4: true
      optional: true
  bridges:
    br0:
      # Change these interface names to match your needs
      interfaces: [enp0s17, wlp5s0]
      dhcp4: true
      optional: true
